#全局端口定义server:
# 全局字符集设置
spring:
  aop:
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true


aliyun:
  accessKeyId: LTAI5tBkx5yHPJtJc2maaoj7
  secret: ah70DssneljMByNzla1oo0Gs2AqldB
  scenes: terrorism
